[package]
name = "matrices"
version = "0.1.0"
authors = ["martyn"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "^0.18"
typenum = "^1.12.0"